-- Session Service schema: charging sessions, panel (auth) users, and stop idempotency.
-- Wallets now live in the Wallet Service; a session records the balance after its own settlement.

CREATE TABLE sessions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    user_id                BIGINT      NOT NULL,
    connector_id           BIGINT      NOT NULL,
    status                 VARCHAR(16) NOT NULL,
    started_at             TIMESTAMPTZ NOT NULL,
    ended_at               TIMESTAMPTZ,
    energy_kwh             NUMERIC(12, 3),
    cost                   NUMERIC(12, 2),
    wallet_balance_after   NUMERIC(12, 2),
    -- Tariff snapshot captured at start, so mid-session price changes never affect this session.
    snapshot_price_per_kwh NUMERIC(12, 2) NOT NULL,
    snapshot_start_fee     NUMERIC(12, 2) NOT NULL,
    snapshot_currency      VARCHAR(3)     NOT NULL,
    CONSTRAINT chk_session_status CHECK (status IN ('ACTIVE', 'COMPLETED'))
);

CREATE INDEX idx_sessions_user ON sessions (user_id);

-- Client-facing idempotency for stop: a repeated stop with the same Idempotency-Key replays the
-- original completed session's receipt instead of re-running billing.
CREATE TABLE stop_idempotency (
    idempotency_key VARCHAR(120) PRIMARY KEY,
    session_id      BIGINT      NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

-- Ops/panel users for Stage 2 auth. Passwords are stored as BCrypt hashes only (seeded at startup).
CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(60)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(16)  NOT NULL,
    CONSTRAINT chk_user_role CHECK (role IN ('VIEWER', 'ADMIN'))
);
