apiVersion: v1
kind: Service
metadata:
  name: session-service
  labels:
    app: session-service
    app.kubernetes.io/part-of: chargesquare
spec:
  selector:
    app: session-service
  ports:
    - port: 8082
      targetPort: 8082
