apiVersion: v1
kind: Service
metadata:
  name: station-service
  labels:
    app: station-service
    app.kubernetes.io/part-of: chargesquare
spec:
  selector:
    app: station-service
  ports:
    - port: 8081
      targetPort: 8081
