apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
    app.kubernetes.io/part-of: chargesquare
spec:
  selector:
    app: wallet-service
  ports:
    - port: 8083
      targetPort: 8083
