-- Station Service schema: the source of truth for physical infrastructure and pricing.

CREATE TABLE stations (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL
);

CREATE TABLE tariffs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_per_kwh  NUMERIC(12, 2) NOT NULL,
    start_fee      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    currency       VARCHAR(3)     NOT NULL
);

CREATE TABLE connectors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT      NOT NULL REFERENCES stations (id),
    tariff_id  BIGINT      NOT NULL REFERENCES tariffs (id),
    type       VARCHAR(40) NOT NULL,
    power_kw   INTEGER     NOT NULL,
    status     VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT chk_connector_status CHECK (status IN ('AVAILABLE', 'OCCUPIED'))
);

CREATE INDEX idx_connectors_station ON connectors (station_id);
